# directory to save pipeline output to
output_dir: "/data/proj/hmcl/drug-screen-manuscript"

# "outlier" cell lines to be removed from downstream steps
outlier_cells: ["KMS11_JCRBsus", "KMS21BM_JCRB", "KMS28BM_JCRB", "Karpas417_ECACC"]

# number of drug clusters to detect?
num_drug_clusters: 9

# number of cell line clusters to detect?
num_cell_clusters: 3

# drugs currently/previously used for myeloma treatment
mm_drugs:
  ids:
    - "NCGC00090851-09"
    - "NCGC00242506-02"
    - "NCGC00249613-03"
    - "NCGC00090759-02"
    - "NCGC00092360-01"
    - "NCGC00093356-08"
    - "NCGC00091019-08"
    - "NCGC00346656-01"
    - "NCGC00181306-03"
    - "NCGC00024415-39"
    - "NCGC00161602-05"
    - "NCGC00165833-04"
    - "NCGC00179504-06"
    - "NCGC00242507-01"
    - "NCGC00346678-01"
    - "NCGC00187912-03"
    - "NCGC00250412-01"
    - "NCGC00167491-02"
    - "NCGC00016564-07"
    - "NCGC00025060-16"
    - "NCGC00345799-01"
    - "NCGC00024995-10"
    - "NCGC00263129-01"
    - "NCGC00263117-02"
    - "NCGC00346551-01"
    - "NCGC00241099-01"
    - "NCGC00021305-08"
    - "NCGC00163470-09"
    - "NCGC00167518-03"
    - "NCGC00188346-01"
    - "NCGC00263180-01"
    - "NCGC00178913-04"
    - "NCGC00345789-01"
  names:
    - "5-Azacitidine"
    - "Bortezomib"
    - "Carfilzomib"
    - "Cisplatin"
    - "Cordycepin"
    - "Cytarabine"
    - "Dexamethasone"
    - "Dinaciclib"
    - "Docetaxel"
    - "Doxorubicin"
    - "Doxycycline"
    - "Entinostat"
    - "Etoposide"
    - "Everolimus"
    - "Ganetespib"
    - "Ibrutinib"
    - "JQ1"
    - "Lenalidomide"
    - "Metformin"
    - "Methotrexate"
    - "Oprozomib"
    - "Paclitaxel"
    - "Palbociclib"
    - "Panobinostat"
    - "Pomalidomide"
    - "Saracatinib"
    - "Sirolimus"
    - "Tacrolimus"
    - "Temsirolimus"
    - "Torkinib"
    - "Trametinib"
    - "Tripterin"
    - "Venetoclax"
