# directory to save pipeline output to
output_dir: "/data/proj/hmcl/drug-screen-manuscript"

# "outlier" cell lines to be removed from downstream steps
outlier_cells: ["KMS11_JCRBsus", "KMS21BM_JCRB", "KMS28BM_JCRB", "Karpas417_ECACC"]
